services:
  con4gis.route_service:
    class: con4gis\RoutingBundle\Classes\Services\RouteService
    public: true
    arguments:
      - "@event_dispatcher"

  con4gis.area_service:
    class: con4gis\RoutingBundle\Classes\Services\AreaService
    public: true
    arguments:
    - "@event_dispatcher"
